services:
  postgres:
    image: postgres:15
    container_name: app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: wortel
      POSTGRES_PASSWORD: "1563"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  shop-main:
    build:
      dockerfile: Dockerfile.shop-main
    container_name: app-shop
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: wortel
      SPRING_DATASOURCE_PASSWORD: "1563"
      SERVER_PORT: 8082
      SERVER_URL: http://app-shop:8082
      YANDEX_DISK_BASE_URL: https://cloud-api.yandex.net/v1/disk
      YANDEX_DISK_WEBDAV_URL: https://webdav.yandex.ru/
      YANDEX_DISK_PUBLIC_URL: https://disk.yandex.ru/client/disk/meshok
      YANDEX_DISK_ACCESS_TOKEN: y0__xCG96bWAxjuwzcg_Z7FghNXXXXXXXXXXXXXXXXXXXXXXXXXXX
      YANDEX_S3_ACCESS_KEY: YCAJEoqWkMNns1jXfYwQtdqIU
      YANDEX_S3_SECRET_KEY: YCN-V0H_cYN41KlMZfKSUi05jLmeWh6nca5EjRGl
      YANDEX_S3_BUCKET: meshok
      YANDEX_S3_ENDPOINT: https://storage.yandexcloud.net
      YANDEX_S3_REGION: ru-central1
      MESHOK_ACCESS_TOKEN: f3cfb2cb5903df0f48231453f1877108
      MESHOK_BASE_URL: https://meshok.net/i/
      SYSTEM_API_KEY_MIGRATION_SERVICE: "migration-service"
      SYSTEM_API_KEY_VALIDITY_DAYS: 30
      MIGRATOR_API_URL: http://app-migrator:8083

  meshok-loader:
    build:
      dockerfile: Dockerfile.meshok-loader
    container_name: app-migrator
    restart: unless-stopped
    depends_on:
      shop-main:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: wortel
      SPRING_DATASOURCE_PASSWORD: "1563"
      SERVER_PORT: 8083
      SERVER_URL: http://app-migrator:8083
      SHOP_URL: http://app-shop:8082
      YANDEX_DISK_BASE_URL: https://cloud-api.yandex.net/v1/disk
      YANDEX_DISK_WEBDAV_URL: https://webdav.yandex.ru/
      YANDEX_DISK_PUBLIC_URL: https://disk.yandex.ru/client/disk/meshok
      YANDEX_DISK_ACCESS_TOKEN: y0__xCG96bWAxjuwzcg_Z7FghNXXXXXXXXXXXXXXXXXXXXXXXXXXX
      MESHOK_ACCESS_TOKEN: f3cfb2cb5903df0f48231453f1877108
      MESHOK_BASE_URL: https://meshok.net/i/

volumes:
  postgres-data: