spring:
  profiles:
    active: dev
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: wortel
    password: "1563"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    jdbc:
      initialize-schema: always

  freemarker:
    template-loader-path: classpath:/templates/
#    username: diakhmadullina@yandex.ru
#    password: ${YANDEX_MAIL_ZEN_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

server:
  port: 8080
  url: http://localhost:8080

debug: true

yandex:
  disk:
    base-url: https://cloud-api.yandex.net/v1/disk
    webdav-url: https://webdav.yandex.ru/
    public-url: https://disk.yandex.ru/client/disk/meshok
    access-token: y0__xCG96bWAxjuwzcg_Z7FghNN0TNgJYEPgT9Tb38nxzKYp-DGjw
  s3:
    access-key: YCAJEoqWkMNns1jXfYwQtdqIU
    secret-key: YCN-V0H_cYN41KlMZfKSUi05jLmeWh6nca5EjRGl
    bucket: meshok
    endpoint: https://storage.yandexcloud.net
    region: ru-central1

meshok:
  access-token: f3cfb2cb5903df0f48231453f1877108
  base-url: https://meshok.net/i/