version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: wortel
      POSTGRES_PASSWORD: "1563"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wortel -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  shop-main:
    build:
      context: ..
      dockerfile: docker/Dockerfile.shop
    container_name: app-shop
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: wortel
      SPRING_DATASOURCE_PASSWORD: "1563"
      SERVER_PORT: 8080
      SERVER_URL: http://shop:8080
      YANDEX_DISK_BASE_URL: https://cloud-api.yandex.net/v1/disk
      YANDEX_DISK_WEBDAV_URL: https://webdav.yandex.ru/
      YANDEX_DISK_PUBLIC_URL: https://disk.yandex.ru/client/disk/meshok
      YANDEX_DISK_ACCESS_TOKEN: y0__xCG96bWAxjuwzcg_Z7FghNXXXXXXXXXXXXXXXXXXXXXXXXXXX
      YANDEX_S3_ACCESS_KEY: YCAJEoqWkMNns1jXfYwQtdqIU
      YANDEX_S3_SECRET_KEY: YCXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      YANDEX_S3_BUCKET: meshok
      YANDEX_S3_ENDPOINT: https://storage.yandexcloud.net
      YANDEX_S3_REGION: ru-central1
      MESHOK_ACCESS_TOKEN: f3cfb2cb5903df0f48231453f1877108
      MESHOK_BASE_URL: https://meshok.net/i/
      SYSTEM_API_KEY_MIGRATION_SERVICE: "migration-service"
      SYSTEM_API_KEY_VALIDITY_DAYS: 30
      MIGRATOR_API_URL: http://migrator:8081

  meshok-loader:
    build:
      context: ..
      dockerfile: docker/Dockerfile.migrator
    container_name: app-migrator
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      shop:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: wortel
      SPRING_DATASOURCE_PASSWORD: "1563"
      SERVER_PORT: 8081
      SERVER_URL: http://migrator:8081
      SHOP_URL: http://shop:8080
      YANDEX_DISK_BASE_URL: https://cloud-api.yandex.net/v1/disk
      YANDEX_DISK_WEBDAV_URL: https://webdav.yandex.ru/
      YANDEX_DISK_PUBLIC_URL: https://disk.yandex.ru/client/disk/meshok
      YANDEX_DISK_ACCESS_TOKEN: y0__xCG96bWAxjuwzcg_Z7FghNXXXXXXXXXXXXXXXXXXXXXXXXXXX
      MESHOK_ACCESS_TOKEN: f3cfb2cb5903df0f48231453f1877108
      MESHOK_BASE_URL: https://meshok.net/i/

volumes:
  postgres-data: