spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:wortel}
    password: ${DATASOURCE_PASSWORD:1563}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
  session:
    jdbc:
      initialize-schema: ${JDBC_INIT_SCHEMA:always}
  thymeleaf:
    prefix: ${THYMELEAF_PREFIX:classpath:/templates/}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}
  task:
    scheduling:
      pool:
        size: ${SCHEDULING_POOL_SIZE:5}

server:
  port: ${SERVER_PORT:8080}
  url: ${SERVER_URL:http://localhost:8080}

yandex:
  disk:
    base-url: ${YANDEX_DISK_BASE_URL:https://cloud-api.yandex.net/v1/disk}
    webdav-url: ${YANDEX_WEBDAV_URL:https://webdav.yandex.ru/}
    public-url: ${YANDEX_PUBLIC_URL:https://disk.yandex.ru/client/disk/meshok}
    access-token: ${YANDEX_ACCESS_TOKEN}
  s3:
    access-key: ${YANDEX_S3_ACCESS_KEY}
    secret-key: ${YANDEX_S3_SECRET_KEY}
    bucket: ${YANDEX_S3_BUCKET:meshok}
    endpoint: ${YANDEX_S3_ENDPOINT:https://storage.yandexcloud.net}
    region: ${YANDEX_S3_REGION:ru-central1}

meshok:
  access-token: ${MESHOK_ACCESS_TOKEN}
  base-url: ${MESHOK_BASE_URL:https://meshok.net/i/}

system:
  api:
    key:
      migration:
        service: ${MIGRATION_SERVICE_KEY:migration-service}
      validity:
        days: ${API_KEY_VALIDITY_DAYS:30}

migrator:
  api:
    url: ${MIGRATOR_API_URL:http://localhost:8083}

springdoc:
  paths-to-match: ${SPRINGDOC_PATHS:/api/**}